### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Cornox** [Longoon12000/DownloadPavlovMapsFromModIo#13]
Hi, I'm getting this error:
![image](https://github.com/user-attachments/assets/4c1f0dc7-ceb2-4338-be0b-dade00864ccf)

I tried to delete the settings.json and re-generate a new OAuth token, but I still get this error.

**Comment by RainOrigami** [comment]
@Cornox thank you for reporting this issue.

You might be running into issue #12 where mod.io rate-limits the API requests.

If you could give this version (https://github.com/RainOrigami/DownloadPavlovMapsFromModIo/issues/12#issuecomment-2132392875) a try, which adds an artificial delay between mod.io requests, it may fix your issue.

Let me know if that works and I'll put this version up as v9 in the releases that this does not happen in the future.

**Comment by Cornox** [comment]
thank you so much :) the solution to #12 fixed the problem.
